// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumidityChange();
void onTemperatureChange();
void onBacklightChange();
void onStatusChange();

float humidity;
float temperature;
int backlight;
bool status;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(backlight, READWRITE, ON_CHANGE, onBacklightChange);
  ArduinoCloud.addProperty(status, READWRITE, ON_CHANGE, onStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
